# SITE CONFIGURATION
title: Artificial Intelligence # your site title
author: Majeed Hussain # You :P
description: > Graduate Student in Computer vision and Robotics # Meta description of Homepage
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://janczizikow.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Majeed
  links:
    - https://twitter.com/majeedhussain49
    - https://www.linkedin.com/in/majeed-hussain49/
    - https://plus.google.com/u/0/118291268535198298869
    - https://github.com/Mjdhsn49
   

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'About', link: '/about'}
  - {name: 'Contact', link: '/contact'}

tagline: >
  A year spent in artificial intelligence is enough to make one believe in God.

hero_img: posts/sleek_lg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: majeedhussain49@gmail.com # email for form submission

twitter_username: majeedhussain49 # replace with your_twitter_username or comment to remove link from footer
github_username:  Mjdhsn49 # replace with your_github_username or comment to remove link from footer
instagram_username:  # replace with your_instagram_username or comment to remove link from footer

disqus:
  shortname: majeed_hussain # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
